version: '3.8'
services:
  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - flask

