name: Flask Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build flask container
      run: docker build . --file Dockerfile --tag flasktesting:$(date +%s)
    - name: build nginx container
      run: docker build ./nginx --file nginx/Dockerfile --tag nginxtesting:$(date +%s)
