name: Deploy to AWS ECR

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::730335382802:role/github-testing-cicd
          aws-region: us-west-1
          role-session-name: GithubActions

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.us-west-1.amazonaws.com

      - name: Build Flask container
        run: docker build . --file Dockerfile --tag flask-app:latest

      - name: Build Nginx container
        run: docker build ./nginx --file nginx/Dockerfile --tag nginx-app:latest

      - name: Tag and push Flask image to Amazon ECR
        run: |
          ECR_REGISTRY=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.us-west-1.amazonaws.com
          docker tag flask-app:latest $ECR_REGISTRY/git22/flask-app:latest
          docker push $ECR_REGISTRY/git22/flask-app:latest

      - name: Tag and push Nginx image to Amazon ECR
        run: |
          ECR_REGISTRY=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.us-west-1.amazonaws.com
          docker tag nginx-app:latest $ECR_REGISTRY/git22/nginx-app:latest
          docker push $ECR_REGISTRY/git22/nginx-app:latest


